# Sigles {.unnumbered}

<!-- Quarto no té suport nadiu de sigles (*acronyms*) -->

| | |
| :--- | :--- |
| **ABI** | *Application Binary Interface* |
| **AC** | Arquitectura de computadors (assignatura del GEI) |
| **ADC** | *Analog-to-Digital Converter* |
| **AMAT** | *Average Memory Access Time* |
| **ALU** | *Arithmetic Logic Unit* |
| **AMO** | *Atomic Memory Operation* |
| **API** | *Application Programming Interface* |
| **ARM** | *Advanced RISC Machines* |
| **ASCII** | *American Standard Code for Information Interchange* |
| **BA** | Bloc d'activació |
| **Ca1** | Complement a u |
| **Ca2** | Complement a dos |
| **CISC** | *Complex Instruction Set Computer* |
| **CPI** | Cicles per instrucció |
| **CPU** | *Central Processing Unit* |
| **CSR** | *Control and Status Register* |
| **CU** | Unitat de control |
| **DRAM** | *Dynamic Random Access Memory* |
| **DVFS** | *Dynamic voltage and frequency scaling* |
| **EC** | Estructura de computadors (assignatura del GEI) |
| **EF** | Examen final |
| **ELF** | *Executable and Linkable Format* |
| **EP** | Examen parcial |
| **E/S** | Entrada/sortida |
| **FIB** | Facultat d'informàtica de Barcelona |
| **FIFO** | *First In, First Out* |
| **GCC** | *GNU Compiler Collection* |
| **GDB** | *GNU Debugger* |
| **GDDR** | *Graphics Double Data Rate* |
| **GEI** | Grau en Enginyeria Informàtica |
| **GND** | *Ground* |
| **GPIO** | *General-Purpose Input/Output* |
| **GPR** | *General-Purpose Registers* |
| **HBM** | *High Bandwidth Memory* |
| **IC** | Introducció als computadors (assignatura del GEI) |
| **IEEE** | *Institute of Electrical and Electronics Engineers* |
| **ISA** | *Instruction Set Architecture* |
| **L1** | Memòria cau de primer nivell |
| **L2** | Memòria cau de segon nivell |
| **L3** | Memòria cau de tercer nivell |
| **LIFO** | *Last in, first out* |
| **LRU** | *Least Recently Used* |
| **LSB** | *Least Significant Byte* |
| **LSb** | *Least Significant bit* |
| **MARS** | *MIPS Assembler and Runtime Simulator* |
| **MC** | Memòria cau |
| **MIPS** | *Microprocessor without Interlocked Pipeline Stages* |
| **MMU** | *Memory Management Unit* |
| **MP** | Memòria principal |
| **MSB** | *Most Significant Byte* |
| **MSb** | *Most Significant bit* |
| **MV** | Memòria virtual |
| **NaN** | *Not a Number* |
| **NMOS** | *n-channel metal–oxide–semiconductor* |
| **NVMe** | *Non-Volatile Memory Express* |
| **OPT** | Algorisme de reemplaçament òptim |
| **PC** | *Program counter* |
| **PIPT** | *Physically Indexed Physically Tagged* |
| **PMOS** | *p-channel metal–oxide–semiconductor* |
| **POSIX** | *Portable Operating System Interface* |
| **PPN** | *Physical Page Number* |
| **PRO1** | Programació I (assignatura del GEI) |
| **PTE** | *Page Table Entry* |
| **RAM** | *Random Access Memory* |
| **RARS** | *RISC-V Assembler and Runtime Simulator* |
| **RISC** | *Reduced Instruction Set Computer* |
| **RNE** | *Round to Nearest Even* |
| **ROM** | *Read Only Memory* |
| **RTZ** | *Round To Zero* (truncament cap a zero) |
| **RSE** | Rutina de servei d'excepcions |
| **RV32F/D** | RISC-V *Floating-point extensions* |
| **RV32I** | RISC-V *Base integer instructions* |
| **RV32M** | RISC-V *Multiply extensions* |
| **RVA20** | Perfil d'aplicació RISC-V de 2020 |
| **RVA22** | Perfil d'aplicació RISC-V de 2022 |
| **RVA23** | Perfil d'aplicació RISC-V de 2023 |
| **S&M** | Signe i magnitud |
| **SM** | *Streaming Multiprocessor* |
| **SO** | Sistema operatiu |
| **SRAM** | *Static Random Access Memory* |
| **SSD** | *Solid-State Drive* |
| **STL** | *Standard Template Library* |
| **SWD** | *Serial Wire Debug* |
| **TAM** | Temps d'accés mitjà |
| **TLB** | *Translation Lookaside Buffer* |
| **UART** | *Universal Asynchronous Receiver-Transmitter* |
| **UI** | *User Interface* |
| **ULP** | *Unit in the Last Place* |
| **VIPT** | *Virtually Indexed Physically Tagged* |
| **VIVT** | *Virtually Indexed Virtually Tagged* |
| **VLSI** | *Very Large Scale Integration* |
| **VPN** | *Virtual Page Number* |
: {tbl-colwidths="[15,85]" .borderless}