project:
  type: book
  output-dir: _book

book:
#  date: "2026-05-04"
  date: last-modified
  title: "Estructura de computadors"
#  subtitle: ""             # Especificat a cada `format:` per adaptar els salts de línia a cada format (HTML <br> vs. PDF \linebreak)
  author: "Professors de l'assignatura"
  sidebar:
    collapse-level: 1       # les `part` comencen col·lapsades al sidebar
  navbar:
    right:
      - icon: filetype-pdf  # https://icons.getbootstrap.com/
        href: Estructura-de-computadors.pdf
      - icon: gitlab
        href: https://gitlab.upc.edu/ec/migracio # `_variables.yml` no es pot usar aquí perquè el `_quarto.yml` s'ha de processar abans que el `_variables.yml`

  chapters:
    - index.qmd
    - part: "Teoria"
      chapters:
        - text: "T1 Introducció"
          file: T1.qmd
        - text: "T2 Instruccions"
          file: T2.qmd
        - text: "T3 Traducció"
          file: T3.qmd
        - text: "T4 Enters i matrius"
          file: T4.qmd
        - text: "T5 Coma flotant"
          file: T5.qmd
        - text: "T6 Rendiment"
          file: T6.qmd
        - text: "T7 Memòria cau"
          file: T7.qmd
        - text: "T8 Memòria virtual"
          file: T8.qmd
        - text: "T9 Interrupcions"
          file: T9.qmd
    - part: "Problemes"
      chapters: 
        - text: "Enunciats"
          file: PE.qmd
        - text: "Solucions"
          file: PS.qmd
    - part: "Laboratori"
      chapters:
        - text: "Calendari"
          file: Lcalendari.qmd
        - text: "S0 Introducció"
          file: L0.qmd
        - text: "S1 RISC-V"
          file: L1.qmd
        - text: "S2 Traducció"
          file: L2.qmd
        - text: "S3 Dades estructurades"
          file: L3.qmd
        - text: "S4 Coma flotant"
          file: L4.qmd
        - text: "S5 Memòria cau"
          file: L5.qmd
    - riscv.qmd
    - sigles.md
    - contrib.qmd
    - LICENSE.md

lang: ca

language:
  crossref-nte-prefix: "RISC-V"         ## `-prefix` Text afegit per Quarto en les referències creuada; e.g. @nte-mult -> "RISC-V 4.1."
  callout-note-title: "RISC-V"          ## `-title` Títol del caption dins del bloc; el del PDF; e.g. "RISC-V 4.1."
  crossref-tip-prefix: "Exemple"
  callout-tip-title: "Exemple"
  crossref-cau-prefix: "Essencial"
  callout-caution-title: "Essencial"
  crossref-wrn-prefix: "Aprofundiment"
  callout-warning-title: "Aprofundiment"
  crossref-imp-prefix: "EC"
  callout-important-title: "EC"

crossref:
  fig-prefix: "Figura"
  fig-title: "Figura"
  tbl-prefix: "Taula"
  tbl-title: "Taula"
  lst-prefix: "Codi"
  lst-title: "Codi"
  thm-prefix: "Algorisme"
  thm-title: "Algorisme"

format:
  html:
#    subtitle: "Grau en Enginyeria Informàtica (GEI) <br> Facultat d'informàtica de Barcelona (FIB) <br> Universitat politècnica de Catalunya (UPC)"
    resources:
      - laboratori/
      - styles.css          # Cal afegir-lo a `resources:` explícitament
#    embed-resources: true  # Incrusta els fitxers de recursos (imatges, fitxers inclosos, etc.) dins del fitxer HTML per evitar problemes de rutes relatives (per exemple, quan es visualitza el fitxer HTML directament des del sistema de fitxers, sense un servidor web)
#    mermaid-format: svg    # Potser que hi ha un bug a Quarto pq les .svg tenen totes `height="480" hardcoded (com a mínim queden espais verticals buits en figures horitzontals)
    mermaid-format: png     # Cal tornar a .svg quan es pugui
    format-links: [pdf]     # Botó a la barra superior per descarregar el PDF
    highlight-style: a11y   # Accessibilitat: Ressaltat de codi adaptatiu
    respect-user-color-scheme: true   # light/dark: per defecte el del sistema
    css:
      - styles.css          # Cal afegir-lo a `resources:` explícitament
    theme:                  # Activació commutador light/dark
      light: 
        - cosmo             # https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/formats/html/bootstrap/themes
        - custom_light.scss
        - custom.scss
      dark:
        - darkly            # cyborg
        - custom_dark.scss
        - custom.scss
    code-line-numbers: true
    code-copy: true         # Icona de "copiar al porta papers"
    number-sections: false  # `left`: Amaga numeració (activada individualment a cada capítol); el comptatge continua encara que no els mostri al `left` ("Presentació" vs. "1 Presentació"); default: `false`
    code-overflow: wrap     # Opcions: `scroll` / `wrap` https://quarto.org/docs/output-formats/html-code.html#code-overflow
    code-fold: true         # https://quarto.org/docs/output-formats/html-code.html#code-tools Permet plegar blocs de codi llargs (més de 20 línies) per millorar la llegibilitat, especialment en dispositius mòbils
    code-tools: true        # Mostra botó `</> Codi` dalt-dreta per mostrar el codi per poder fer C&P https://quarto.org/docs/output-formats/html-code.html#code-tools
    toc: true
    toc-location: left      # "Taula de continguts" a `left`
    page-layout: full       # Estén el frame central sobre el dret (per aprofitar l'espai que deixa `toc-location: left`)
  pdf:
    header-includes: \AtBeginDocument{\subtitle{Departament d'Arquitectura de Computadors \linebreak \linebreak Grau en Enginyeria Informàtica \linebreak Facultat d'informàtica de Barcelona \linebreak Universitat politècnica de Catalunya}\date{\today}}
    documentclass: scrbook  # KOMA: `scrartcl` (~10 pàg.), `scrreport` (~50 pàg.), `scrbook` (+50 pàg.)
    classoption: oneside    # KOMA: `oneside`, `twoside`
    papersize: a4           # KOMA: `a4` (default), `letter`
    geometry:
      - top=1.5cm
      - bottom=1cm
      - left=2cm
      - right=2cm
      - includeheadfoot
      - footskip=1cm
    fontsize: 11pt
    number-sections: true
    keep-tex: true          # Conserva el fitxer .tex generat per Pandoc
    colorlinks: true   # Activa el color en els enllaços (per defecte són vermells)
    urlcolor: blue     # Color per als enllaços web (URLs externos)
    linkcolor: blue    # Color per als enllaços interns (índex, seccions, etc.)
    citecolor: blue    # Color per a les cites bibliogràfiques
    include-in-header:
      - text: |
          \usepackage{fvextra}
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\},fontsize=\small}    % Blocs de codi amb salt de línia automàtic i `fontsize=\small`
          \usepackage{scrlayer-scrpage}
          \pagestyle{scrheadings}
          \clearpairofpagestyles
          \ihead{\headmark}
          \ofoot{\thepage}

bibliography: bibliografia.bib
csl: ieee.csl
