---
subtitle: "Departament d'Arquitectura de Computadors"
---

# Presentació {.unnumbered}

**[Estructura de Computadors](https://www.fib.upc.edu/ca/graus/grau-en-enginyeria-informatica/pla-destudis/assignatures/EC)** (**EC**) és una assignatura **obligatòria** de 7,5 crèdits del [Grau en Enginyeria Informàtica](https://www.fib.upc.edu/ca/graus/grau-en-enginyeria-informatica) (GEI) de la [Facultat d'Informàtica de Barcelona](https://www.fib.upc.edu) (FIB), impartida pel [Departament d'Arquitectura de Computadors](https://www.ac.upc.edu) (DAC) de la Universitat Politècnica de Catalunya (UPC).[^assignaturesgeifib]

[^assignaturesgeifib]: Totes les assignatures esmentades en aquests apunts són del Grau en Enginyeria Informàtica (GEI) de la Facultat d'Informàtica de Barcelona (FIB), si no s'especifica explícitament el contrari.

L'assignatura tracta de l'organització bàsica en què s'estructura un computador per donar suport als llenguatges de programació d'alt nivell: tant els tipus de dades que utilitzen els programes com les sentències de control més habituals. L'eix vertebrador és la relació entre el **maquinari** (***hardware***) i el **programari** (***software***) a través del nivell d'abstracció de l'**arquitectura del repertori d'instruccions** (***Instruction Set Architecture***, **ISA**).[^migraciorv]

[^migraciorv]: A partir del curs 2025/26, l'arquitectura de referència de l'assignatura és **RISC-V** (variant **RV32I**, extensions **M**, **F** i **RV32IZicsr**); anteriorment havia estat MIPS.

::: {#sec-presentacio-avaluacio}
::: {.content-visible unless-format="pdf"}
## ✅️ Avaluació
:::
::: {.content-visible when-format="pdf"}
## Avaluació
:::
:::

### Nota final

::: {.content-visible when-format="pdf"}
La **nota final ($\text{NF}$)** s'obté a partir de:

- **Teoria i problemes (NT)**: $80\%$ de $\text{NF}$. Distribució:
  - Examen parcial (EP): $0.20 \cdot \max\{\text{EP}, \text{EF}\}$
  - Examen final (EF): $0.60 \cdot \text{EF}$
- **Laboratori (NL)**: $20\%$ de $\text{NF}$. Distribució:
  - Examen de laboratori (EL): $85\%$ de $\text{NL}$
  - Avaluació continuada (AC): $15\%$ de $\text{NL}$
:::
::: {.content-visible when-format="html"}
La **nota final (<math><mi>NF</mi></math>)** s'obté a partir de:

- **Teoria i problemes (NT)**: <math><mn>0.80</mn><mo>%</mo></math> de <math><mi>NF</mi></math>. Distribució:
  - Examen parcial (EP): <math><mn>0.20</mn><mo>&#x22C5;</mo><mi>max</mi><mo>{</mo><mi>EP</mi><mo>,</mo><mi>EF</mi><mo>}</mo></math>
  - Examen final (EF): <math><mn>0.60</mn><mo>&#x22C5;</mo><mi>EF</mi></math>
- **Laboratori (NL)**: <math><mn>0.20</mn><mo>%</mo></math> de <math><mi>NF</mi></math>. Distribució:
  - Examen de laboratori (<mi>EL</mi>): <math><mn>0.85</mn><mo>%</mo></math> <math><mi>NL</mi></math>
  - Avaluació continuada (<mi>AC</mi>): <math><mn>0.15</mn><mo>%</mo></math> de <math><mi>NL</mi></math>
:::

Per tant:

::: {.content-visible unless-format="html"}
$$\text{NF} = 0.20 \cdot \max\{\text{EP}, \text{EF}\} + 0.60 \cdot \text{EF} + 0.20 \cdot (0.85 \cdot \text{EL} + 0.15 \cdot \text{AC})$$
:::
::: {.content-visible when-format="html"}
<math display="block">
  <mi>NF</mi>
  <mo>=</mo>
  <mrow>
    <mn>0.20</mn>
    <mo>&#x22C5;</mo>
    <mrow>
      <mi>max</mi>
      <mo>{</mo>
      <mi>EP</mi>
      <mo>,</mo>
      <mi>EF</mi>
      <mo>}</mo>
    </mrow>
  </mrow>
  <mo>+</mo>
  <mrow>
    <mn>0.60</mn>
    <mo>&#x22C5;</mo>
    <mi>EF</mi>
  </mrow>
  <mo>+</mo>
  <mrow>
    <mn>0.20</mn>
    <mo>&#x22C5;</mo>
    <mrow>
      <mo>(</mo>
      <mrow>
        <mn>0.85</mn>
        <mo>&#x22C5;</mo>
        <mi>EL</mi>
      </mrow>
      <mrow>
        <mo>+</mo>
        <mn>0.15</mn>
        <mo>&#x22C5;</mo>
        <mi>AC</mi>
      </mrow>
      <mo>)</mo>
    </mrow>
  </mrow>
</math>
:::

::: {#sec-presentacio-avaluacio-ep}
::: {.content-visible unless-format="pdf"}
### 📖️ Examen parcial: temari
:::
::: {.content-visible when-format="pdf"}
### Examen parcial: temari
:::
:::

- [Teoria](#sec-presentacio-eines-teoria): [Tema 1](#sec-tema-introduccio), [Tema 2](#sec-tema-assemblador), [Tema 3](#sec-tema-traduccio), [Tema 4](#sec-tema-enters-matrius).
    - [Tema 5](#sec-tema-coma-flotant): En cas de no haver-se pogut acabar abans de l'EP, el professor indicarà a l'aula fins a quina secció s'avaluarà.
- [Laboratori](#sec-presentacio-eines-laboratori): [Sessió 0](#sec-sessio-introduccio), [Sessió 1](#sec-sessio-assemblador), [Sessió 2](#sec-sessio-traduccio), [Sessió 3](#sec-sessio-dades-estructurades).
    - [Sessió 4](#sec-sessio-coma-flotant): En cas de no haver-se pogut acabar abans de l'EP, el professor indicarà a l'aula fins a quina secció s'avaluarà.

::: {#sec-presentacio-avaluacio-ef}
::: {.content-visible unless-format="pdf"}
### 📖️ Examen final: temari
:::
::: {.content-visible when-format="pdf"}
### Examen final: temari
:::
:::

- [Teoria](#sec-presentacio-eines-teoria): Tot.
- [Problemes](#sec-presentacio-eines-problemes): Tot.
- [Laboratori](#sec-presentacio-eines-laboratori): Tot.

::: {#sec-presentacio-avaluacio-laboratori}
::: {.content-visible unless-format="pdf"}
### ⚗️ Laboratori
:::
::: {.content-visible when-format="pdf"}
### Laboratori
:::
:::

- L'**Avaluació continuada** Mitjana de les notes de les 6 sessions. 
    - **Treball previ**: Treball que s'ha de lliurar al [Racó](https://raco.fib.upc.edu/) abans de l'inici de la sessió (excepte per a la Sessió 0) per **poder ser avaluat a la pràctica**. Consisteix en lliurar els fitxers de cada sessió. No s'exigeix que les respostes siguin totalment correctes, però sí suficientment completes per assegurar que durant la pràctica s'obtingui una nota positiva.
    - **Nota de la sessió**: L'avaluació es fa individualment **durant la pràctica** a través de la verificació la validesa de les respostes als exercicis i de les respostes a les preguntes que pugui fer el professor. **És responsabilitat de l'estudianta d'avisar amb temps suficient al professor perquè l'avalu-hi.**
- **Examen de Laboratori**: Es realitza **individualment** en un **PC dels laboratoris docents**. És responsabilitat de l'alumne assegurar-se:
    - Abans de l'examen, de disposar d'almenys 10 MB d'espai lliure en la seva zona de disc per poder baixar i editar els fitxers de l'examen.
    - Durant l'examen, de lliurar els fitxers de la solució **dins del termini** temporal establert.
        - **No hi ha límit de lliuraments**. Sempre s'avaluarà només la darrera versió de cada fitxer.

:::  {#sec-presentacio-avaluacio-competencia-transversal}
::: {.content-visible unless-format="pdf"}
### 🌿️ Competència transversal
:::
::: {.content-visible when-format="pdf"}
### Competència transversal
:::
:::

La competència transversal treballada a EC és **Sostenibilitat i Compromís Social** (**G2**), amb èmfasi en la relació entre rendiment i consum elèctric dels computadors. S'avalua mitjançant un problema específic de l'EF. La nota d'aquest problema també es té en compte per al càlcul de la nota de l'EF.

::: {#sec-presentacio-eines}
::: {.content-visible unless-format="pdf"}
## 🛠️ Eines i materials per a l'estudi
:::
::: {.content-visible when-format="pdf"}
## Eines i materials per a l'estudi
:::
:::

::: {#sec-presentacio-eines-teoria}
::: {.content-visible unless-format="pdf"}
### 📘 Teoria
:::
::: {.content-visible when-format="pdf"}
### Teoria
:::
:::

- [Tema 1: Introducció](#sec-tema-introduccio)
- [Tema 2: Instruccions i tipus de dades bàsics](#sec-tema-assemblador)
- [Tema 3: Traducció de programes](#sec-tema-traduccio)
- [Tema 4: Aritmètica entera i matrius](#sec-tema-enters-matrius)
- [Tema 5: Coma flotant](#sec-tema-coma-flotant)
- [Tema 6: Rendiment i potència](#sec-tema-rendiment-potencia)
- [Tema 7: Memòria cau](#sec-tema-mc)
- [Tema 8: Memòria virtual](#sec-tema-mv)
- [Tema 9: Excepcions i interrupcions](#sec-tema-excepcions-interrupcions)

| Color | Icona | Tipus | Matèria avaluable | Contingut |
| :---: | :---: | :--- | :---: | :--- |
| <span style="display:inline-block;width:12px;height:12px;border-radius:2px;background-color:#198754;margin-right:6px"></span> | <span style="font-family:'bootstrap-icons';color:#198754">&#xf2d6;</span> | RISC-V        | **Sí** | Referències tècniques |
| <span style="display:inline-block;width:12px;height:12px;border-radius:2px;background-color:#0539f6;margin-right:6px"></span> | <span style="font-family:'bootstrap-icons';color:#0539f6">&#xf333;</span> | Criteri EC    | **Sí** | Criteris de l'assignatura |
| <span style="display:inline-block;width:12px;height:12px;border-radius:2px;background-color:#c0392b;margin-right:6px"></span> | <span style="font-family:'bootstrap-icons';color:#c0392b">&#xf26b;</span> | Essencial     | **Sí** | Contingut indispensable |
| <span style="display:inline-block;width:12px;height:12px;border-radius:2px;background-color:#ebca11;margin-right:6px"></span> | <span style="font-family:'bootstrap-icons';color:#ebca11">&#xf46b;</span> | Exemple       | **Sí** | Exemples il·lustratius |
| <span style="display:inline-block;width:12px;height:12px;border-radius:2px;background-color:#8e44ad;margin-right:6px"></span> | <span style="font-family:'bootstrap-icons';color:#8e44ad">&#xf308;</span> | Aprofundiment | No | Contingut opcional |
: Requadres de text. Significat i rellevància. {#tbl-requadres-tipus tbl-colwidths="[20, 20, 25,35,55]" style="width: 80%; margin: auto;"}

::: {#sec-presentacio-eines-problemes}
::: {.content-visible unless-format="pdf"}
### 📝 Problemes
:::
::: {.content-visible when-format="pdf"}
### Problemes
:::
:::

- [Enunciats de problemes](#sec-problemes-enunciats): Col·lecció d'exercicis.
- [Solucions seleccionades](#sec-problemes-solucions): Resolució d'una selecció d'exercicis de la col·lecció d'exercicis.

::: {#sec-presentacio-eines-laboratori}
::: {.content-visible unless-format="pdf"}
### ⚗️ Laboratori
:::
::: {.content-visible when-format="pdf"}
### Laboratori
:::
:::

- [Sessió 0: Introducció](#sec-sessio-introduccio)
- [Sessió 1: Assemblador](#sec-sessio-assemblador)
- [Sessió 2: Traducció de programes](#sec-sessio-traduccio)
- [Sessió 3: Dades estructurades](#sec-sessio-dades-estructurades)
- [Sessió 4: Coma flotant](#sec-sessio-coma-flotant)
- [Sessió 5: Memòria cau](#sec-sessio-mc)

::: {#sec-presentacio-eines-rars}
::: {.content-visible unless-format="pdf"}
### 💻️ El simulador (RARS)
:::
::: {.content-visible when-format="pdf"}
### El simulador (RARS)
:::
:::

És totalment:

- **Indispensable** per al laboratori.
- **Recomanat** per a l'assignatura en general.
    - Davant de qualsevol dubte relatiu al llenguatge d'assemblador, és recomanable desenvolupar un exemple mínim (*minimal working example*, MWE) i experimentar-hi.
    - Als materials, hi ha fragments de codi que poden servir d'orientació.

**Treballar amb codi de manera habitual és una manera molt efectiva d'aclarir i consolidar conceptes.**

#### Instal·lació

1. Descarregueu i guardeu el fitxer [`rars1_6.jar`](https://github.com/TheThirdOne/rars/releases/download/v1.6/rars1_6.jar) de la versió de referència[referències tècniques](#sec-presentacio-referencies). <a href="laboratori/rars1_6.jar" download>Còpia local</a>
2. Descarregueu i guardeu el fitxer <a href="laboratori/startup.s" download>`laboratori/startup.s`</a>.
    - Al laboratori ha d'estar a un **subdirectori de `/home/`**; a <!--- cSpell:disable --->`/assigs/`<!--- cSpell:enable ---> **no funciona**!
3. Descarregueu i instal·leu [Java Runtime Environment (JRE)](https://www.java.com/en/download/help/download_options.html) versió 8.0 o superior.

#### Inicialització

1. Obriu un terminal (GNU/Linux: Ctrl+Alt+T).
2. Aneu al directori de `rars1_6.jar` (per exemple amb la comanda `cd <DIR_FULL_PATH>`).
3. Executeu: `java -jar rars1_6.jar`.

#### Configuració inicial (només una vegada!)

1. *Settings* → *Exception Handler...*
    1. Activació del *checkbox* (✓☑): *Include this exception handler file in all assemble operations*
    2. Botó *Browse*: selecció del fitxer `startup.s`
    3. Botó *OK*

::: {#sec-presentacio-eines-gcc}
::: {.content-visible unless-format="pdf"}
### ⚙️ El compilador (GNU/GCC)
:::
::: {.content-visible when-format="pdf"}
### El compilador (GNU/GCC)
:::
:::

- També és **totalment recomanat** per a l'assignatura en general.
    - Pels mateixos motius que per al codi d'assemblador.
    - Als materials, també hi ha fragments de codi com a orientació.

::: {#sec-presentacio-eines-raco}
::: {.content-visible unless-format="pdf"}
### 🌐️ [El Racó](https://raco.fib.upc.edu/)
:::
::: {.content-visible when-format="pdf"}
### [El Racó](https://raco.fib.upc.edu/)
:::
:::

- Avisos/Notícies
    - Convocatòria d'exàmens
    - Comunicacions dels professors i distribució de material (diapositives, exercicis addicionals, etc.)
- Laboratori
    - Estudis previs
    - Examen
- Exàmens d'anys anteriors
    - Enunciats
    - Solucions

::: {#sec-presentacio-eines-pagina-assignatura}
::: {.content-visible unless-format="pdf"}
### 🌐️ [Pàgina de l'assignatura](https://docencia.ac.upc.edu/FIB/grau/EC/)
:::
::: {.content-visible when-format="pdf"}
### [Pàgina de l'assignatura](https://docencia.ac.upc.edu/FIB/grau/EC/)
:::
:::

- Grups
- Professors
- Dates de laboratori

::: {#sec-presentacio-eines-guia-docent}
::: {.content-visible unless-format="pdf"}
### 🌐️ [Guia docent (FIB)](https://www.fib.upc.edu/ca/graus/grau-en-enginyeria-informatica/pla-destudis/assignatures/EC)
:::
::: {.content-visible when-format="pdf"}
### [Guia docent (FIB)](https://www.fib.upc.edu/ca/graus/grau-en-enginyeria-informatica/pla-destudis/assignatures/EC)
:::
:::

- Competències
- Objectius
- Rol de l'assignatura dins del pla d'estudis

## Referències tècniques {#sec-presentacio-referencies}

Les referències següents estableixen els criteris tècnics segons els quals s'avaluarà.

:::: {#imp-llenguatges-de-referencia .callout-important}
## Referències tècniques de l'assignatura {#sec-presentacio-referencies-llenguatges}

<!-- TODO Determinar versió la ISO de C? -->
<!-- TODO La ISO de C és tancada? -->
<!-- TODO GCC cal especificar millor -->
<!-- TODO Consolidar noms, versions, etc. de tot -->
<!-- TODO Versió numèrica de CSR o de data a la resta -->
::: {tbl-colwidths="[25,25,55]" style="width: 90%; margin: auto;"}
| Ítem | Nom | Estàndard |
| :--- | :--- | :--- |
| Llenguatge d'alt nivell | C | [ISO/IEC 9899:2024 (C23)](https://open-std.org/JTC1/SC22/WG14/www/docs/n3854.pdf) |
| Compilador C^1^ | GNU/GCC | [GCC 15](https://gcc.gnu.org/gcc-15/) |
| Llenguatge d'assemblador | RISC-V (32 bits) | [RV32I Base Integer Instruction Set, Version 2.1](https://docs.riscv.org/reference/isa/unpriv/rv32.html) <br> [Control and Status Registers (CSRs), 20260120](https://docs.riscv.org/reference/isa/priv/priv-csrs.html) <br>["M" Extension for Integer Multiplication and Division, Version 2.0](https://docs.riscv.org/reference/isa/unpriv/m-st-ext.html) <br> ["F" Extension for Single-Precision Floating-Point, Version 2.2](https://docs.riscv.org/reference/isa/unpriv/f-st-ext.html) <br> ["Zicsr" Extension for Control and Status Register (CSR) Instructions, Version 2.0](https://docs.riscv.org/reference/isa/unpriv/zicsr.html) |
| Simulador^1^ | RARS (32 bits) | [RARS -- RISC-V Assembler and Runtime Simulator v1.6](https://github.com/TheThirdOne/rars/tree/v1.6) |
| Toolchain | `riscv32-unknown-elf-gcc` | [RISC-V GNU Compiler Toolchain](https://github.com/riscv-collab/riscv-gnu-toolchain) |
| Sistema operatiu | GNU/Linux | Qualsevol distribució generalista |
:::

^1^ En cas de conflicte RARS preval sobre el compilador.
::::

::: {#sec-presentacio-bibliografia}
::: {.content-visible unless-format="pdf"}
## 📚️ Bibliografia
:::
::: {.content-visible when-format="pdf"}
## Bibliografia
:::
:::

::: {#refs}
:::

::: {#sec-presentacio-bibliografia-complementaria}
::: {.content-visible unless-format="pdf"}
## 📚️ Bibliografia Complemenetària
:::
::: {.content-visible when-format="pdf"}
## Bibliografia Complemenetària
:::
:::

- [RISC-V Reader: An Open Architecture Atlas](https://riscvbook.com/) (David Patterson i Andrew Waterman, 2017). Versió en castellà: <!--- cSpell:disable --->[RISC-V Reader: Un atlas de arquitectura abierta](http://www.riscvbook.com/spanish/) (David Patterson y Andrew Waterman, 2017. Traducció de Alí Lemus, Eduardo Corpeño). <!--- cSpell:enable --->