---
number-sections: true
---

# Sessió 0: Introducció {#sec-sessio-introduccio}

## Lliuraments {.unnumbered}

Aquesta sessió, **només aquesta**, no té lliuraments associats.

## Lectura prèvia {.unnumbered}

TODO

## "Hello World!"

A continuació es presenta el primer programa que escriurem en RISC-V: el clàssic "Hello, World!", present a l'inici de molts manuals de programació. L'@exr-hello-world imprimeix el missatge "Hola, món!" a la consola i ens permetrà familiaritzar-nos amb la sintaxi bàsica de l'assemblador RISC-V i amb les directives per emmagatzemar dades i codi.

---

::: {#exr-hello-world}
## s0_1_1.s

Escriu un programa en RISC-V que imprimeixi "Hola, món!" a la consola. Utilitza les directives adequades per emmagatzemar la cadena i el codi al segment de text.
:::

**Nota**: La solució utilitza els recursos que encara no s'han vist a Teoria següents:

* Les etiquetes globals (@nte-globl).
* El pas de paràmetres (@sec-pas-parametres-retorn).
* Les crides al sistema (`ecall`, @sec-ecall) i els codis de servei (@sec-ecall-abi).

Per ara no cal que les entengueu. Només que les utilitzeu tal com s'indica a la solució i **incorporeu-les a tots els programes que feu**. No patiu, durant el curs s'aniran tractant totes.

::: {#cau-hello-world .callout-caution}
De moment no enteneu les instruccions i directrius marcades amb `[futur]`, però incorporeu-les a tots els programes que feu.
:::

---

::: {#sol-hello-world}
```{.s filename="hello_world.s"}
.global _start          # [futur]

.data                   # Secció de variables globals
msg:    .asciz "Hola, món!"

.text                   # Secció de codi
_start:                 # [futur]
        # Escriure el missatge a la consola
        la  a0, msg     # Adreça del missatge
        li  a7, 4       # [futur] Codi de servei per imprimir una cadena acabada amb `\0` a la consola
        ecall           # [futur] Crida al sistema per imprimir el missatge

        li  a0, 0       # [futur] Codi d'error (0 finalització exitosa)
        li  a7, 93      # [futur] Codi de sortida amb codi de sortida (***exit code***) a `a0`
        ecall           # [futur] Crida al sistema per sortir del programa
```


:::

---
