---
number-sections: true
---

# {{< var tema1 >}} {#sec-tema-introduccio-enunciats}

## El cicle de vida del programa: Generació vs. Execució

::: {#exr-p1-jerarquia-python}
Volem executar un programa escrit en Python en un ordinador RISC-V, però només disposem dels elements següents:

- Un compilador de C a llenguatge màquina x86-64, escrit en llenguatge màquina x86-64.
- Un traductor binari de llenguatge màquina x86-64 a llenguatge màquina RISC-V, escrit en llenguatge màquina RISC-V.
- Un intèrpret de Python, escrit en C.

Quins passos cal fer per executar el programa en Python en l'ordinador RISC-V, usant solament els elements disponibles?
:::

::: {#exr-p1-jerarquia-c}
Volem executar un programa escrit en C en un ordinador x86-64, però només disposem dels elements següents:

- Un intèrpret de Python, escrit en llenguatge màquina RISC-V.
- Un compilador de C a llenguatge màquina x86-64, escrit en Python.
- Un traductor de llenguatge màquina RISC-V a llenguatge màquina x86-64, escrit en llenguatge màquina x86-64.

a) Quins passos cal fer per executar el programa en C en l'ordinador x86-64, usant solament els elements disponibles?
b) Quins passos caldria fer si es vol tornar a executar el mateix programa?
:::
